trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: GoTool@0
    inputs:
      version: '1.22'

  - script: |
      go build -o cli
      ./cli "echo hello"
    displayName: 'Build the Go application'